### ISSUE TITLE
GCC optimalizations.

### ISSUE THREAD

**Issue by miegl** [tanaka1892/PiFmAdv#1]
Hey,
I wouldn't really recommend compiling PiFmAdv with `-O3` as it will lead to stability problems. `-O2` is the highest you can go without breaking things.

**Comment by Anthony96922** [comment]
Using `-O3` reduces CPU usage to about 35% on a Raspberry Pi 1. Because I reduced the usleep value there are no RDS bit errors like there were before.

**Comment by miegl** [comment]
There are still stability issues that are hard to debug. I advise for not using -O3 optimizations, if you want to save yourself from experiencing weird stability problems.

**Comment by Anthony96922** [comment]
`-O2` seems to be a good compromise. Fixed in 757071cd1d44a09c4f41193a06d6288b44909d2d
